// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhtozjkvrlzpmzcdcvmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpodG96amt2cmx6cG16Y2Rjdm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNjY0MTYsImV4cCI6MjA0OTc0MjQxNn0.wVWLfTQs3M10yG6XBCgYlhpppbg96YngwQ_htqYwu6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);